### ISSUE TITLE
Pass time and period to new JointController update in send_to_slave()

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/GazeboXBotPlugin#10]
devel branch.

As title: send_to_slave after the HAL refactor does not have a straightforward way to retrieve time and period.

Maybe also @alaurenzi  can help.

Currently I am passing 0.0

**Comment by alaurenzi** [comment]
We found the solution, did we not?

**Comment by liesrock** [comment]
We did find it (6dae0b3e36954b632197ecea1fb49c0917edebb9) !
