### ISSUE TITLE
time

### ISSUE THREAD

**Issue by nkashiri** [ADVRHumanoids/GazeboXBotPlugin#11]
I'm running the same plugin on the devel branch, and in comparison with what I had run on the master branch, the robot motions are much faster. 
My guess is that the plugin takes the real time, and not the simulation time, as a trajectory to be done in 10s takes 10s in real time, and not 10s in simulation time.

**Comment by pepperig** [comment]
try to pull devel branch of GazeboXbotPlugin and XBotCore. Compile them and let me know!

**Comment by nkashiri** [comment]
Thanks @pepperig
