### ISSUE TITLE
Wheel Position

### ISSUE THREAD

**Issue by nkashiri** [ADVRHumanoids/GazeboXBotPlugin#14]
The issue was 
The error was because the reading from SRDF would give a crazy value (-1430699352826875165473343331663954301079744180889263858133343537097379776078180717224420423150387673277708180048169908077285156199011630493666933329297611304043150464150901362011111980467072256312999228543900784959949733107118614164443947583096973270838787239397294080.00 ) for a joint whose position was not actually defined.

**Comment by nkashiri** [comment]
@pepperig @liesrock @alaurenzi It can be also an issue for the robot since the the ankle yaw homing positions in SRDF of the robot are also missing.

**Comment by alaurenzi** [comment]
The getRobotState function should set to zero all components of the q vector that are not explicitly defined inside the srdf. If this is not the case, it is a bug and the cause must be investigated! I reopen the issue till we clarify this

**Comment by nkashiri** [comment]
The only problem is that, at least on my system, it's very random. For 100 times of running, the issue may not appear. But today I was lucky to have it 4-5 times, specifically when I was trying to move to a posture whose ankle pitches were not defined (I thought the ankle yaw was missing, but actually the ankle pitch value was missing). 
The output of getRobotState was giving the random value on the "16+1"th element (v[16]), which is an ankle yaw though! 
But, after completing the SRDF positions, it has not happened again so far. It might be random, or may be relevant.

**Comment by nkashiri** [comment]
I confirm there is no problem is not from getRobotState. I didn't initialise the Eigen vector, and ...
