### ISSUE TITLE
Decouple GazeboPlugin from PluginHandler

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/GazeboXBotPlugin#8]
Currently the GazeboXBotPlugin emulates the behavior of the XBotCore, so we have common code duplicated like the pluginHandler. The idea is to have a generic GazeboPlugin that acts as a Server able to receive command and send fedback of the sensors.
We need to remove the pluginHandler and leave just the interface with gazebo robot.
The goal is to run just XBotCore and then chose at runtime if you want to be attached to the simulator or to the real robot. In the case of simulator, the calls to IXBotJoint ecc, will be forwarded to the Gazebo using RPC or other network methods.  All the design will follow the HAL on the XBotCore(HAL) branch.
I have some paper showing the design and we can check it together. 
@alaurenzi @liesrock  @EnricoMingo

**Comment by alaurenzi** [comment]
To me this is difficult to achieve without sacrificing the RT performance. Even in simulation, exchanging data between the two processes will cause delays which are difficult to quantify.

**Comment by liesrock** [comment]
@pepperig I think you achieved it right? Can you update/close this issue?

**Comment by pepperig** [comment]
It is partly achieved. The missing part is related to GazeboPlugin act as a Server.
